/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_markazandroid_advertiser_hardware_serial_SerialPort */

#ifndef _Included_ir_markazandroid_advertiser_hardware_serial_SerialPort
#define _Included_ir_markazandroid_advertiser_hardware_serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_markazandroid_advertiser_hardware_serial_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_ir_markazandroid_advertiser_hardware_serial_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     ir_markazandroid_advertiser_hardware_serial_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ir_markazandroid_advertiser_hardware_serial_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
